services:
  - type: web
    name: judge0-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 2358
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: enabled
      - key: DATABASE_URL
        fromDatabase:
          name: judge0-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: judge0-redis
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DISABLE_TELEMETRY
        value: "true"
    dockerCommand: "docker run -p 2358:2358 judge0/api:latest"
    autoDeploy: false

databases:
  - name: judge0-db
    plan: free

services:
  - type: redis
    name: judge0-redis
    plan: free
